# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunbo',
            name='img',
            field=models.CharField(max_length=520),
        ),
    ]
